name: Build & Publish Bot

on:
  push:
    branches:
     - main
    paths:
     - "src/TwitchDropsDiscordBot"
     - ".github/workflows/bot.yml"
  pull_request:
    paths:
     - "src/TwitchDropsDiscordBot"
     - ".github/workflows/bot.yml"

jobs:
  build:
    name: Build & Publish Bot
    runs-on: "ubuntu-latest"

    env:
      BOT_CSPROJ_PATH: src/TwitchDropsDiscordBot/TwitchDropsDiscordBot.csproj
      BOT_OUTPUT_FOLDER: ./TwitchDropsDiscordBot
      DOTNET_CONFIGURATION: Release
      DOTNET_SERVER_GC: false
      IS_MAIN: ${{ github.ref == 'refs/heads/main' }}
    
    steps:
      - name: "Src: Checkout"
        uses: actions/checkout@v5
      
      - name: ".NET: Install SDK"
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"
      
      - name: ".NET: Restore"
        run: dotnet restore ${{ env.BOT_CSPROJ_PATH }}
      
      - name: ".NET: Build"
        run: dotnet build ${{ env.BOT_CSPROJ_PATH }} --configuration ${{ env.DOTNET_CONFIGURATION }} --no-restore /p:ServerGarbageCollection=${{ env.DOTNET_SERVER_GC }}
      
      - name: ".NET: Publish"
        run: dotnet publish ${{ env.BOT_CSPROJ_PATH }} --configuration ${{ env.DOTNET_CONFIGURATION }} --no-restore --no-build --output ${{ env.BOT_OUTPUT_FOLDER }} /p:ServerGarbageCollection=${{ env.DOTNET_SERVER_GC }}

      # I'm using built-in .NET functionality to list basic dependency version info (list outdated, deprecated or vulnerable packages).
      # Whilst using dependabot or snyk may be beneficial here, I'm trying to avoid using third party libraries or services here, and dependabot is overkill
      # since I want to be in control of the dependencies, not having them auto-upgrade. There are valid reasons to remain on outdated versions, such as bugs.
      # These 3 "dotnet list package" commands will not fail the build if values are returned. They are purely informational.
      - name: ".NET: List Outdated Dependencies"
        run: dotnet list ${{ env.BOT_CSPROJ_PATH }} package --outdated

      - name: ".NET: List Deprecated Dependencies"
        run: dotnet list ${{ env.BOT_CSPROJ_PATH }} package --deprecated

      - name: ".NET: List Vulnerable Dependencies"
        run: dotnet list ${{ env.BOT_CSPROJ_PATH }} package --vulnerable --include-transitive

      - name: "Publish: Bot Artifact"
        if: ${{ env.IS_MAIN == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: TwitchDropsDiscordBot
          path: ${{ env.BOT_OUTPUT_FOLDER }}
          compression-level: 9 # Refers to ZLib compression levels (between 0(none) and 9(heavily compressed))
          if-no-files-found: error
